//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add Extensions\MyQuantityExtensions.cs to decorate quantities with new behavior.
//     Add UnitDefinitions\MyQuantity.json and run GeneratUnits.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Copyright (c) 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com).
// https://github.com/angularsen/UnitsNet
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

using System;

// Windows Runtime Component does not support extension methods and method overloads: https://msdn.microsoft.com/en-us/library/br230301.aspx
#if !WINDOWS_UWP
namespace UnitsNet.Extensions.NumberToFlow
{
    public static class NumberToFlowExtensions
    {
        #region CentilitersPerMinute

        /// <inheritdoc cref="Flow.FromCentilitersPerMinute(UnitsNet.QuantityValue)" />
        public static Flow CentilitersPerMinute<T>(this T value) => Flow.FromCentilitersPerMinute(Convert.ToDouble(value));

        #endregion

        #region CubicDecimeterPerMinute

        /// <inheritdoc cref="Flow.FromCubicDecimetersPerMinute(UnitsNet.QuantityValue)" />
        [System.Obsolete("Deprecated due to github issue #363, please use VolumeFlow instead")]
        public static Flow CubicDecimetersPerMinute<T>(this T value) => Flow.FromCubicDecimetersPerMinute(Convert.ToDouble(value));

        #endregion

        #region CubicFootPerHour

        /// <inheritdoc cref="Flow.FromCubicFeetPerHour(UnitsNet.QuantityValue)" />
        [System.Obsolete("Deprecated due to github issue #363, please use VolumeFlow instead")]
        public static Flow CubicFeetPerHour<T>(this T value) => Flow.FromCubicFeetPerHour(Convert.ToDouble(value));

        #endregion

        #region CubicFootPerMinute

        /// <inheritdoc cref="Flow.FromCubicFeetPerMinute(UnitsNet.QuantityValue)" />
        [System.Obsolete("Deprecated due to github issue #363, please use VolumeFlow instead")]
        public static Flow CubicFeetPerMinute<T>(this T value) => Flow.FromCubicFeetPerMinute(Convert.ToDouble(value));

        #endregion

        #region CubicFootPerSecond

        /// <inheritdoc cref="Flow.FromCubicFeetPerSecond(UnitsNet.QuantityValue)" />
        [System.Obsolete("Deprecated due to github issue #363, please use VolumeFlow instead")]
        public static Flow CubicFeetPerSecond<T>(this T value) => Flow.FromCubicFeetPerSecond(Convert.ToDouble(value));

        #endregion

        #region CubicMeterPerHour

        /// <inheritdoc cref="Flow.FromCubicMetersPerHour(UnitsNet.QuantityValue)" />
        [System.Obsolete("Deprecated due to github issue #363, please use VolumeFlow instead")]
        public static Flow CubicMetersPerHour<T>(this T value) => Flow.FromCubicMetersPerHour(Convert.ToDouble(value));

        #endregion

        #region CubicMeterPerMinute

        /// <inheritdoc cref="Flow.FromCubicMetersPerMinute(UnitsNet.QuantityValue)" />
        [System.Obsolete("Deprecated due to github issue #363, please use VolumeFlow instead")]
        public static Flow CubicMetersPerMinute<T>(this T value) => Flow.FromCubicMetersPerMinute(Convert.ToDouble(value));

        #endregion

        #region CubicMeterPerSecond

        /// <inheritdoc cref="Flow.FromCubicMetersPerSecond(UnitsNet.QuantityValue)" />
        [System.Obsolete("Deprecated due to github issue #363, please use VolumeFlow instead")]
        public static Flow CubicMetersPerSecond<T>(this T value) => Flow.FromCubicMetersPerSecond(Convert.ToDouble(value));

        #endregion

        #region CubicYardPerHour

        /// <inheritdoc cref="Flow.FromCubicYardsPerHour(UnitsNet.QuantityValue)" />
        [System.Obsolete("Deprecated due to github issue #363, please use VolumeFlow instead")]
        public static Flow CubicYardsPerHour<T>(this T value) => Flow.FromCubicYardsPerHour(Convert.ToDouble(value));

        #endregion

        #region CubicYardPerMinute

        /// <inheritdoc cref="Flow.FromCubicYardsPerMinute(UnitsNet.QuantityValue)" />
        [System.Obsolete("Deprecated due to github issue #363, please use VolumeFlow instead")]
        public static Flow CubicYardsPerMinute<T>(this T value) => Flow.FromCubicYardsPerMinute(Convert.ToDouble(value));

        #endregion

        #region CubicYardPerSecond

        /// <inheritdoc cref="Flow.FromCubicYardsPerSecond(UnitsNet.QuantityValue)" />
        [System.Obsolete("Deprecated due to github issue #363, please use VolumeFlow instead")]
        public static Flow CubicYardsPerSecond<T>(this T value) => Flow.FromCubicYardsPerSecond(Convert.ToDouble(value));

        #endregion

        #region DecilitersPerMinute

        /// <inheritdoc cref="Flow.FromDecilitersPerMinute(UnitsNet.QuantityValue)" />
        public static Flow DecilitersPerMinute<T>(this T value) => Flow.FromDecilitersPerMinute(Convert.ToDouble(value));

        #endregion

        #region KilolitersPerMinute

        /// <inheritdoc cref="Flow.FromKilolitersPerMinute(UnitsNet.QuantityValue)" />
        public static Flow KilolitersPerMinute<T>(this T value) => Flow.FromKilolitersPerMinute(Convert.ToDouble(value));

        #endregion

        #region LitersPerHour

        /// <inheritdoc cref="Flow.FromLitersPerHour(UnitsNet.QuantityValue)" />
        [System.Obsolete("Deprecated due to github issue #363, please use VolumeFlow instead")]
        public static Flow LitersPerHour<T>(this T value) => Flow.FromLitersPerHour(Convert.ToDouble(value));

        #endregion

        #region LitersPerMinute

        /// <inheritdoc cref="Flow.FromLitersPerMinute(UnitsNet.QuantityValue)" />
        [System.Obsolete("Deprecated due to github issue #363, please use VolumeFlow instead")]
        public static Flow LitersPerMinute<T>(this T value) => Flow.FromLitersPerMinute(Convert.ToDouble(value));

        #endregion

        #region LitersPerSecond

        /// <inheritdoc cref="Flow.FromLitersPerSecond(UnitsNet.QuantityValue)" />
        [System.Obsolete("Deprecated due to github issue #363, please use VolumeFlow instead")]
        public static Flow LitersPerSecond<T>(this T value) => Flow.FromLitersPerSecond(Convert.ToDouble(value));

        #endregion

        #region MicrolitersPerMinute

        /// <inheritdoc cref="Flow.FromMicrolitersPerMinute(UnitsNet.QuantityValue)" />
        public static Flow MicrolitersPerMinute<T>(this T value) => Flow.FromMicrolitersPerMinute(Convert.ToDouble(value));

        #endregion

        #region MillilitersPerMinute

        /// <inheritdoc cref="Flow.FromMillilitersPerMinute(UnitsNet.QuantityValue)" />
        public static Flow MillilitersPerMinute<T>(this T value) => Flow.FromMillilitersPerMinute(Convert.ToDouble(value));

        #endregion

        #region MillionUsGallonsPerDay

        /// <inheritdoc cref="Flow.FromMillionUsGallonsPerDay(UnitsNet.QuantityValue)" />
        [System.Obsolete("Deprecated due to github issue #363, please use VolumeFlow instead")]
        public static Flow MillionUsGallonsPerDay<T>(this T value) => Flow.FromMillionUsGallonsPerDay(Convert.ToDouble(value));

        #endregion

        #region NanolitersPerMinute

        /// <inheritdoc cref="Flow.FromNanolitersPerMinute(UnitsNet.QuantityValue)" />
        public static Flow NanolitersPerMinute<T>(this T value) => Flow.FromNanolitersPerMinute(Convert.ToDouble(value));

        #endregion

        #region OilBarrelsPerDay

        /// <inheritdoc cref="Flow.FromOilBarrelsPerDay(UnitsNet.QuantityValue)" />
        [System.Obsolete("Deprecated due to github issue #363, please use VolumeFlow instead")]
        public static Flow OilBarrelsPerDay<T>(this T value) => Flow.FromOilBarrelsPerDay(Convert.ToDouble(value));

        #endregion

        #region UsGallonsPerHour

        /// <inheritdoc cref="Flow.FromUsGallonsPerHour(UnitsNet.QuantityValue)" />
        [System.Obsolete("Deprecated due to github issue #363, please use VolumeFlow instead")]
        public static Flow UsGallonsPerHour<T>(this T value) => Flow.FromUsGallonsPerHour(Convert.ToDouble(value));

        #endregion

        #region UsGallonsPerMinute

        /// <inheritdoc cref="Flow.FromUsGallonsPerMinute(UnitsNet.QuantityValue)" />
        [System.Obsolete("Deprecated due to github issue #363, please use VolumeFlow instead")]
        public static Flow UsGallonsPerMinute<T>(this T value) => Flow.FromUsGallonsPerMinute(Convert.ToDouble(value));

        #endregion

        #region UsGallonsPerSecond

        /// <inheritdoc cref="Flow.FromUsGallonsPerSecond(UnitsNet.QuantityValue)" />
        [System.Obsolete("Deprecated due to github issue #363, please use VolumeFlow instead")]
        public static Flow UsGallonsPerSecond<T>(this T value) => Flow.FromUsGallonsPerSecond(Convert.ToDouble(value));

        #endregion

    }
}
#endif
